August 5: 1. Creating arrays. How to make a matrix.

In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [3]:
print(my_array1)

[1 2 3 4]


In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

my_lists = [my_list1 , my_list2]

In [6]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [7]:
my_array2= np.array(my_lists)

In [8]:
print(my_array2)

[[ 1  2  3  4]
 [11 22 33 44]]


In [30]:
list1 = ["a","b","c","d"]
list2 = [4,5,6,7]

array_test = np.array([list1, list2])

In [10]:
lists = [list1, list2]

In [11]:
array_test = np.array(lists)

In [12]:
print(array_test)

[['a' 'b' 'c' 'd']
 ['4' '5' '6' '7']]


In [13]:
my_array2.shape #2 X 4

(2, 4)

In [14]:
my_array2.dtype

dtype('int64')

In [15]:
help(dtype)

NameError: name 'dtype' is not defined

In [16]:
array_test.dtype

dtype('<U1')

In [17]:
array_test.shape

(2, 4)

<<<< Special cases array: zeros, ones, empty, eye, arange. >>>>

In [18]:
np.zeros(5) #Creating array 1X5 with zeros.

array([0., 0., 0., 0., 0.])

In [19]:
my_zeros_array = np.zeros(5)

In [20]:
my_zeros_array.dtype # elements in the array has float64

dtype('float64')

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([1.49166815e-154, 1.49166815e-154, 1.48219694e-323, 0.00000000e+000,
       0.00000000e+000])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,40,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39])

In [26]:
np.arange([5,10],[2,10])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

    2. Using arrays and scalars.

In [27]:
5/2

2.5

In [28]:
from __future__ import division

In [31]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [32]:
arr1 

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [33]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [34]:
arr1*2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [35]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
arr1-5

array([[-4, -3, -2, -1],
       [ 3,  4,  5,  6]])

In [37]:
1 /arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [38]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

3.Indexing arrys

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[1]

1

In [42]:
arr3 = np.arange(9,19)

In [43]:
arr3[4]

13

In [44]:
arr3

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [45]:
arr3[1:6]

array([10, 11, 12, 13, 14])

In [46]:
arr3[0:5]

array([ 9, 10, 11, 12, 13])

In [47]:
arr3[0:5] = 100

In [48]:
arr3

array([100, 100, 100, 100, 100,  14,  15,  16,  17,  18])

In [49]:
arr = np.arange(0,11)

In [50]:
slice_of_arr = arr[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:] = 99

In [53]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()

In [56]:
arr_copy[:] = 1

In [57]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [60]:
arr_2d.shape

(3, 3)

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[1] #row

array([20, 25, 30])

In [77]:
arr_2d[0,2]

15

In [64]:
arr_2d[1,1] #reaching individual elements 

25

In [65]:
arr_2d[1][1]

25

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Note: The result includes the start index, but excludes the end index.

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[:2,1:] # first part: row / second part: colum. make sure last number doesn't include and find the overraped part

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [69]:
arr_2d[:1,1:2]

array([[10]])

In [83]:
arr_2d[2]

array([35, 40, 45])

In [84]:
arr_2d = np.zeros((10,10))

In [85]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
arr_length = arr_2d.shape[1]
print(arr_length)

10


In [91]:
for i in range(arr_length):
    arr_2d[i] = 1

print(arr_2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [92]:
for i in range(arr_length):
    arr_2d[i] = i

print(arr_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [93]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [70]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [71]:
print(arr[2] + arr[3])

7


In [74]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr2)

print(arr2[0, 1]) #[row, colum]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [75]:
print(arr2[1, 4])

10


In [76]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3)

print(arr3[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [80]:
arr_11 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_11)
print(arr_11[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [81]:
print(arr_11[0:2, 2])

[3 8]


In [82]:
print(arr_11[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<<<<<<<<< Arry Transposition >>>>>>>>>>

In [1]:
import numpy as np

In [2]:
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
arr.T #transpose 10X5 to 5X10

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [4]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [6]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [11]:
np1 = np.arange(4)
np2 = np.arange(3,7)

print(np1)
print(np2)

[0 1 2 3]
[3 4 5 6]


In [13]:
np.dot(np1,np2)

32

In [14]:
arr3d = np.arange(50).reshape(5,5,2)
print(arr3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]]


In [15]:
arr3d.T

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [17]:
arr3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [18]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [19]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

In [23]:
arr4 = np.arange(1,5).reshape(2,2)
arr4

array([[1, 2],
       [3, 4]])

In [27]:
arr4.swapaxes(0,1)

array([[1, 3],
       [2, 4]])

<<<<<< Universal Array Functions >>>>>>>

In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)
print(A)

[ 1.61965706 -0.41073994 -1.1534848   0.78050575  1.63138407 -0.75409974
  0.41549009  1.02537565 -0.42732975  1.41277639]


In [8]:
B = np.random.randn(10)
print(B)

[-0.43265027 -1.97366741 -0.19947112  1.11276664  0.71800803  0.96046282
 -0.55679809  0.07702461 -0.92084758 -1.63972094]


In [9]:
#Binary Functions:
np.add(A,B)

array([ 1.18700679, -2.38440735, -1.35295592,  1.89327239,  2.3493921 ,
        0.20636308, -0.141308  ,  1.10240026, -1.34817733, -0.22694456])

In [10]:
np.maximum(A,B)

array([ 1.61965706, -0.41073994, -0.19947112,  1.11276664,  1.63138407,
        0.96046282,  0.41549009,  1.02537565, -0.42732975,  1.41277639])

In [12]:
np.minimum(A,B)

array([-0.43265027, -1.97366741, -1.1534848 ,  0.78050575,  0.71800803,
       -0.75409974, -0.55679809,  0.07702461, -0.92084758, -1.63972094])

In [13]:
web = "https://numpy.org/doc/stable/reference/arrays.nditer.html"
import webbrowser
webbrowser.open(web)

True